// 회원 관련 TABLE--------------------------------------------------------
// 기존 테이블 DROP
DROP TABLE SAVE_LIST;
DROP TABLE POST_LIKE;
DROP TABLE POST_IMG;
DROP TABLE POST_TAG;
DROP TABLE POST_HASHTAG;
DROP TABLE HASHTAG;
DROP TABLE POST_COMMENTS_LIKE;
DROP TABLE POST_COMMENT;
DROP TABLE POST;
DROP TABLE PICK;
DROP TABLE MESSAGE_IMG;
DROP TABLE WON_MESSAGE;
DROP TABLE ERROR_POST_COMMENT;
DROP TABLE ERROR_POST;
DROP TABLE MEMBER;
DROP SEQUENCE SEQ_ERR_POST_NO;

// 회원관련 TABLE 추가
CREATE TABLE MEMBER(
    USER_ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(200) NOT NULL,
    USER_NAME VARCHAR2(15) NOT NULL,
    NICK_NAME VARCHAR2(20) UNIQUE NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    PHONE VARCHAR2(19) UNIQUE NOT NULL,
    GENDER VARCHAR2(6) NOT NULL,
    BIRTH DATE,
    ADDRESS VARCHAR2(100),
    INTRODUCE VARCHAR2(100),
    P_IMG VARCHAR2(300),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N', 'A'))
);

CREATE TABLE PICK(
    USER_ID VARCHAR2(20) REFERENCES MEMBER,
    PICKED_ID VARCHAR2(20) REFERENCES MEMBER
);


CREATE TABLE HASHTAG(
    HASHTAG_ID NUMBER PRIMARY KEY,
    HASHTAG VARCHAR2(30) NOT NULL UNIQUE
);


CREATE TABLE POST (
    POST_ID NUMBER PRIMARY KEY,
    USER_ID REFERENCES MEMBER,
    POST_CONTENT VARCHAR2(300),
    POSTING_TIME DATE NOT NULL
);


CREATE TABLE POST_IMG(
    IMG_ID NUMBER PRIMARY KEY,
    POST_ID REFERENCES POST,
    FILE_NAME VARCHAR2(225) NOT NULL
);


CREATE TABLE POST_TAG(
    POST_ID NUMBER REFERENCES POST,
    TAGGED_USER_ID REFERENCES MEMBER
);


CREATE TABLE POST_LIKE(
    POST_ID REFERENCES POST,
    USER_ID REFERENCES MEMBER
);


CREATE TABLE POST_HASHTAG(
    HASHTAG_ID REFERENCES HASHTAG,
    POST_ID REFERENCES POST
);


CREATE TABLE POST_COMMENT(
    POST_COMMENT_ID NUMBER PRIMARY KEY,
    USER_ID REFERENCES MEMBER,
    POST_ID REFERENCES POST,
    POST_COMMENT VARCHAR2(100) NOT NULL
);


CREATE TABLE POST_COMMENTS_LIKE( 
    COMMENT_ID REFERENCES POST_COMMENT,
    USER_ID REFERENCES MEMBER
);


CREATE TABLE WON_MESSAGE(
    MESSAGE_ID NUMBER PRIMARY KEY,
    MS_SENDER REFERENCES MEMBER,
    MS_RECEIVER REFERENCES MEMBER,
    MESSAGE_TEXT VARCHAR2(300) NOT NULL,
    MESSAGE_TIME DATE NOT NULL
);



CREATE TABLE MESSAGE_IMG(
    IMG_ID NUMBER PRIMARY KEY,
    USER_ID REFERENCES MEMBER,
    MESSAGE_ID REFERENCES WON_MESSAGE,
    FILE_NAME VARCHAR2(225) NOT NULL
);


CREATE TABLE SAVE_LIST(
    SAVE_LIST_ID NUMBER PRIMARY KEY,
    USER_ID REFERENCES MEMBER,
    SAVED_POST_ID REFERENCES POST
);


CREATE TABLE ERROR_POST(
    ERROR_POST_ID NUMBER PRIMARY KEY,
    USER_ID REFERENCES MEMBER,
    POSTING_DATE DATE NOT NULL,
    ERROR_CONTENT VARCHAR2(600) NOT NULL
);

CREATE SEQUENCE SEQ_ERR_POST_NO;

CREATE TABLE ERROR_POST_COMMENT(
    ERROR_POST_ID REFERENCES ERROR_POST,
    COMMENT_DATE DATE NOT NULL,
    COMMENT_TEXT VARCHAR2(600) NOT NULL
);

--// 알림 관련 TABLE 추후 추가
--DROP TABLE NOTICE;
--
--CREATE TABLE NOTICE(
--);







